trigger:
- main

pool:
  name: NagashreeAgent

steps:

- checkout: self
  displayName: 'Checkout Source Code'

- task: Maven@4
  displayName: 'Build Maven Project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\Java\jdk-17'
    mavenVersionOption: 'Default'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'drop'
    publishLocation: 'Container'